// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/pricing" | "/privacy-policy" | "/*";
  };
  "pages/home/index.tsx": {
    id: "pages/home/index";
    page: "/";
  };
  "pages/about/index.tsx": {
    id: "pages/about/index";
    page: "/about";
  };
  "pages/pricing/index.tsx": {
    id: "pages/pricing/index";
    page: "/pricing";
  };
  "pages/privacy-policy/index.tsx": {
    id: "pages/privacy-policy/index";
    page: "/privacy-policy";
  };
  "pages/not-found/index.tsx": {
    id: "pages/not-found/index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./source/root.tsx");
  "pages/home/index": typeof import("./source/pages/home/index.tsx");
  "pages/about/index": typeof import("./source/pages/about/index.tsx");
  "pages/pricing/index": typeof import("./source/pages/pricing/index.tsx");
  "pages/privacy-policy/index": typeof import("./source/pages/privacy-policy/index.tsx");
  "pages/not-found/index": typeof import("./source/pages/not-found/index.tsx");
};