import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import type { ClarifyPlugin, ClarifyUISlotName } from '../types.js'

const GENERATED_FILE_NAME = 'clarify-env.d.ts'

const GENERATED_HEADER = `// This file is generated by Clarify. Do not edit it manually.
// It provides ambient type declarations for Clarify virtual modules used in
// plugin and slot code, so the TypeScript language service can resolve them.
`

/**
 * Slot names known to Clarify, used as the literal union in the generated
 * `virtual:clarify-slot` declaration. Plugin-declared slots are validated
 * against the renderer's `ClarifyUISlotName`, so we only emit the built-in set.
 */
const BUILT_IN_SLOT_NAMES: ClarifyUISlotName[] = ['page.footer.before', 'page.banner.replace', 'page.footer.replace']

function collectSlotNames(plugins: ClarifyPlugin[]): ClarifyUISlotName[] {
  const names = new Set<ClarifyUISlotName>(BUILT_IN_SLOT_NAMES)
  for (const plugin of plugins) {
    for (const slot of plugin.slots ?? []) {
      names.add(slot.name)
    }
  }
  return [...names]
}

export function generateClarifyEnvDts(plugins: ClarifyPlugin[]): string {
  const slotNames = collectSlotNames(plugins)
  const slotNameUnion = slotNames.map(name => `    | ${JSON.stringify(name)}`).join('\n')

  return `${GENERATED_HEADER}
declare module 'virtual:clarify-slot' {
  import type { ComponentType } from 'react'
  import type { RouteItem } from '@clarify-labs/renderer'

  export type ClarifyUISlotName =
${slotNameUnion}

  export type ClarifySlotContext = {
    name: ClarifyUISlotName
    plugin: string
    route?: RouteItem
    locale?: string
    config?: Record<string, unknown>
    DefaultComponent?: ComponentType
  }

  export function useClarifySlot(): ClarifySlotContext
}

declare module 'virtual:clarify-runtime-slots' {
  import type { ComponentType } from 'react'

  export type RuntimeSlotEntry = {
    plugin: string
    component: ComponentType
    config?: Record<string, unknown>
  }

  export const runtimeSlots: Record<string, RuntimeSlotEntry[]>
}
`
}

/**
 * Writes `clarify-env.d.ts` into the project root. Only rewrites when content
 * changes to avoid triggering unnecessary file watchers, and never overwrites a
 * user-authored file that does not carry the generated marker.
 */
export function writeClarifyEnvDts(projectRoot: string, plugins: ClarifyPlugin[]): void {
  const filePath = join(projectRoot, GENERATED_FILE_NAME)
  const next = generateClarifyEnvDts(plugins)

  if (existsSync(filePath)) {
    const current = readFileSync(filePath, 'utf-8')
    if (current === next) return
    // Guard against clobbering a hand-written file that happens to share the name.
    if (!current.startsWith('// This file is generated by Clarify.')) return
  }

  writeFileSync(filePath, next, 'utf-8')
}
