import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import type { ClarifyPlugin } from '../types.js'

const GENERATED_FILE_NAME = 'clarify-env.d.ts'

/**
 * Template for the generated `clarify-env.d.ts` file.
 * Edit this template directly if you need to change the type declarations.
 * This avoids the complexity of reading external files at runtime after bundling.
 */
const CLARIFY_ENV_TEMPLATE = `// This file is generated by Clarify. Do not edit it manually.
// It provides ambient type declarations for Clarify virtual modules used in
// plugin and slot code, so the TypeScript language service can resolve them.

declare module 'virtual:clarify/slot' {
  import type { ClarifyUISlotName, ClarifySlotContext } from '@clarify-labs/cli'

  export { ClarifyUISlotName, ClarifySlotContext }

  export function useClarifySlot(): ClarifySlotContext
}

declare module 'virtual:clarify/slots' {
  import type { ComponentType } from 'react'

  export type RuntimeSlotEntry = {
    plugin: string
    /** Lazy import factory — yields the default-exported React component. */
    component: () => Promise<{ default: ComponentType }>
  }

  export const runtimeSlots: Record<string, RuntimeSlotEntry[]>
}
`

export function generateClarifyEnvDts(_plugins: ClarifyPlugin[]): string {
  return CLARIFY_ENV_TEMPLATE
}

/**
 * Writes `clarify-env.d.ts` into the project root. Only rewrites when content
 * changes to avoid triggering unnecessary file watchers, and never overwrites a
 * user-authored file that does not carry the generated marker.
 */
export function writeClarifyEnvDts(projectRoot: string, plugins: ClarifyPlugin[]): void {
  const filePath = join(projectRoot, GENERATED_FILE_NAME)
  const next = generateClarifyEnvDts(plugins)

  if (existsSync(filePath)) {
    const current = readFileSync(filePath, 'utf-8')
    if (current === next) return
    // Guard against clobbering a hand-written file that happens to share the name.
    if (!current.startsWith('// This file is generated by Clarify.')) return
  }

  writeFileSync(filePath, next, 'utf-8')
}
